name: "pytest"

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Install
        run: |
          pip install -U pip
          pip install -U setuptools
          pip install pytest coverage pytest-cov
          pip install -e .
      - name: Pytest
        run: |
          pytest --cov=tensorclouds tests
      - name: Coverage
        run: |
          coverage html -d _build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _build/
          force_orphan: true
